### ISSUE TITLE
a:visited et al.

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#40]
```SCSS
a { color: $wvu-base-link-color; text-decoration: underline;
  &:visited { color: $wvu-visited-link-color; text-decoration: none; }
  &:active { text-decoration: none; }
  &:hover { color: $wvu-hover-link-color; text-decoration: underline; }
} //a
```
This section should be turned into a mixin that is controlled via a overrideable variable.  Often times using other SCSS frameworks setting a:visited directly interferes with cascading styles and you'll have to redefined the visited active and hover over and over on multiple styles.  It would be nice to be able to easily switch this section off if you dont want to include it.

Suggestion:

```SCSS
$wvu-use-typography-ahref: true !default;

@mixin wvu-typography-ahref  {
  a { color: $wvu-base-link-color; text-decoration: underline;
    &:visited { color: $wvu-visited-link-color; text-decoration: none; }
    &:active { text-decoration: none; }
    &:hover { color: $wvu-hover-link-color; text-decoration: underline; }
  } //a
}

@if $wvu-use-typography-ahref {
  @include wvu-typography-ahref;
}
```
