### ISSUE TITLE
Implement Font-face-observer to prevent FOIT

### ISSUE THREAD

**Issue by adamjohnson** [wvuweb/brand-patterns#48]
FOIT = Flash of Invisible Text, aka, this at 1.3-1.4 seconds:

![FOIT Example](https://cloud.githubusercontent.com/assets/575865/9855110/5ddde5d6-5ada-11e5-8c1b-f0a35c6b0003.png)

Text disappears when loading the correct @font-face font.

The solution to prevent FOIT is to use Bram Stien's [Font-Face-Observer](https://github.com/bramstein/fontfaceobserver) which can add a `fonts-loaded` class to the `<html>` tag. The CSS would look something like this:

```css
body { font-family: Arial, sans-serif; }
.fonts-loaded body { font-family: "Helvetica Neue", Arial, sans-serif; } 
```

[This article](https://jonsuh.com/blog/font-loading-with-font-events/) is particularly helpful. This has [already been implemented](https://stash.development.wvu.edu/projects/CST/repos/admissions/commits/a9d1f02150d0f0e8d4b7c9a2c19ed4c4be6c4d29) for Admissions. 

This should happen after #47 has been closed.

**Comment by adamjohnson** [comment]
This commit is relevant to this issue as it cleans up the JS for Font-Face-Observer:

https://stash.development.wvu.edu/projects/CST/repos/admissions/commits/92ec6da1ba030b4a435cdaf0a4a75528b41f21d9

**Comment by adamjohnson** [comment]
Font Face Observer has been implemented for Helvetica Neue Light and Black Condensed. If you use Iowan for your site, you'll have to add it under `"fonts" : []` in `fontfaceobserver__custom.js` and provide the resulting Sass. The Sass would probably look something like this:

```scss
.iowan-old-style { font-family: Georgia, 'Times New Roman', Times, serif; font-weight: normal;
  .fonts-loaded & { font-family: $iowan-old-style; }
}
```

If you don't implement FFO for Iowan, normal behavior will ensue and you'll see a FOIT until the font loads.

Vignet [posted a great article](https://viget.com/extend/the-font-face-dilemma) about FFO & others. Leaving it here for reference.
