### ISSUE TITLE
Double applied position padding and Media Query

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#70]
Line 2 of : [scss/3-layouts/_wvu-base.scss](https://github.com/wvuweb/brand-patterns/blob/master/scss/3-layouts/_wvu-base.scss) includes the mixin `@mixin wvu-container` which has `position` and `paddings` set, and then the position and paddings are set again after the mixin call.

A cleaned up file would look like this:

```SCSS
@mixin wvu-container {
  @include outer-container(); position: relative; padding: $wvu-container-padding; padding-left: 1em; padding-right: 1em;
  @include mq($bp-xlarge) {
    padding: $wvu-container-padding; padding-left: 0; padding-right: 0;
  }
}

.wvu-container {
  @include outer-container();
}

.main {
  @include mq($bp-medium) { @include span-columns(9); }
}

.wvu-sidebar {
  @include mq($bp-medium) { @include span-columns(3); }
}
```
