### ISSUE TITLE
Dry up scss/3-layouts/_wvu-base

### ISSUE THREAD

**Issue by zeroedin** [wvuweb/brand-patterns#71]
There is duplication of code in `scss/3-layouts/_wvu-base`  could rewrite the file to:

```SCSS
.wvu-container {
  @include wvu-container();
}

@mixin wvu-container {
  @include outer-container(); position: relative; padding: $wvu-container-padding; padding-left: 1em; padding-right: 1em;
  @include mq($bp-xlarge) {
    padding: $wvu-container-padding; padding-left: 0; padding-right: 0;
  }
}

.main {
  @include mq($bp-medium) { @include span-columns(9); }
}

.wvu-sidebar {
  @include mq($bp-medium) { @include span-columns(3); }
}
```
